spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/sb_batch?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name:
    username: Aruming
    password: Aruming
  jpa:
    show-sql: true